FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY ./scraper.sln /app/
COPY ./Scraper.Web /app/Scraper.Web/
COPY ./Scraper.Domain /app/Scraper.Domain/
COPY ./Scraper.DataAccess /app/Scraper.DataAccess/

ENV PATH $PATH:/root/.dotnet/tools
RUN dotnet tool install --global dotnet-ef
RUN dotnet publish

ENTRYPOINT dotnet-ef database update --project /app/Scraper.Web/ --startup-project /app/Scraper.Web/ -- --environment Prod
