FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY ./scraper.sln /app/
COPY ./Scraper.Web /app/Scraper.Web/
COPY ./Scraper.Domain /app/Scraper.Domain/
COPY ./Scraper.Archiver /app/Scraper.Archiver/
COPY ./Scraper.DataAccess /app/Scraper.DataAccess/
COPY ./Scraper.Common /app/Scraper.Common/

RUN dotnet publish


FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build /app/Scraper.Archiver/bin/Release/net8.0 /app/

ENTRYPOINT ["dotnet", "Scraper.Archiver.dll"]