services:
    zookeeper:
        container_name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 2181:2181

    kafka-broker:
        image: confluentinc/cp-kafka:7.2.1
        container_name: scraper-kafka-broker
        ports:
            - 9092:9092
            - 9093:9093
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: INSIDE://scraper-kafka-broker:9092,OUTSIDE://localhost:9093
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        healthcheck:
            test: [ "CMD-SHELL", "nc -z localhost 9092 || exit -1" ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s
        depends_on:
            - zookeeper

    selenium-hub:
        container_name: scraper-selenium-hub
        image: selenium/hub:latest
        ports:
            - 4444:4444
        healthcheck:
            test: [ "CMD-SHELL", "curl -s http://localhost:4444/wd/hub/status | grep -q 'ready'" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    chrome-node:
        container_name: scraper-chrome-node
        image: selenium/node-chrome:latest
        environment:
            - SE_EVENT_BUS_HOST=scraper-selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        depends_on:
            - selenium-hub

    scraper-database:
        container_name: scraper-database
        image: mcr.microsoft.com/mssql/server
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=abcd1234_efg
            - MSSQL_PID=Developer
        ports:
            - 21433:1433
        healthcheck:
            test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P abcd1234_efg -C -Q 'SELECT 1'" ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s

    scraper-migrations:
        container_name: scraper-migrations
        build:
            dockerfile: Dockerfile.scraper-migrations
            context: .
        depends_on:
            - scraper-database

    scraper-web:
        container_name: scraper-web
        build:
            dockerfile: Dockerfile.scraper-web
            context: .
        ports:
            - 5000:8080
        depends_on:
            selenium-hub:
                condition: service_healthy
            kafka-broker:
                condition: service_healthy
            scraper-database:
                condition: service_healthy
